version: '3.5'

services:
  app:
    stdin_open: true
    tty: true
    restart: on-failure:1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
      - app-node-cache:/usr/app/node_modules
    ports:
      - ${APP_HTTP_PORT:-3000}:3000

volumes:
  app-node-cache:
    name: app-node-cache
